on: push
name: Ejecutar tests al hacer push
jobs:
   test:
      runs-on: ubuntu-latest 
      steps:
        - name: 'Clonar y revision de la rama actual'
           uses: actions/checkout@v1
        - name: Instalar dependencias
          run: yarn install
        - name: Ejecutando test
           run: yarn test
